name: validate
on:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - "main"
      - "next"
      - "next-major"
      - "beta"
      - "alpha"
      - "!all-contributors/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      fail-fast: false
      matrix:
        eslint: [6, 7, 8, 9, 10]
        node: [12.x, 14.x, 16.x, 18.x, 20.x, 21.x, 22.x, 24.x]
        testing-library-dom: [8, 9, 10]
        exclude:
          - eslint: 9
            node: 12.x
          - eslint: 9
            node: 14.x
          - eslint: 9
            node: 16.x
          - eslint: 10
            node: 12.x
          - eslint: 10
            node: 14.x
          - eslint: 10
            node: 16.x
          - eslint: 10
            node: 18.x
          - eslint: 10
            node: 21.x
          - testing-library-dom: 9
            node: 12.x
          - testing-library-dom: 10
            node: 12.x
          - testing-library-dom: 10
            node: 14.x
          - testing-library-dom: 10
            node: 16.x
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

        # see https://github.com/npm/cli/issues/7349
      - if: ${{ matrix.eslint >= 9 }}
        run: npm un @typescript-eslint/parser

      - name: Install ESLint v${{ matrix.eslint }}
        run: npm install --no-save --force eslint@${{ matrix.eslint }}

      - name: Install @testing-library/dom v${{ matrix.testing-library-dom }}
        run: npm install --no-save --force @testing-library/dom@${{ matrix.testing-library-dom }}

      - name: Install TypeScript v4
        if: ${{ matrix.node == '12.x' }}
        run: npm install --no-save --force typescript@4

      - name: â–¶ï¸ Run validate script (without linting)
        if: ${{ matrix.eslint != 8 }}
        run: npm run validate -- build,test:coverage

      - name: â–¶ï¸ Run validate script (with linting)
        if: ${{ matrix.eslint == 8 }}
        run: npm run validate

      - name: â–¶ï¸ Ensure docs are up-to-date
        if: ${{ matrix.eslint == 8 && matrix.node != '12.x' }}
        run: npm run lint:generate-readme-table

      - name: â¬†ï¸ Upload coverage report
        uses: codecov/codecov-action@v3

  release:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'testing-library/eslint-plugin-jest-dom' &&
      contains('refs/heads/main,refs/heads/beta,refs/heads/next,refs/heads/alpha',
      github.ref) && github.event_name == 'push' }}
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ğŸ— Run build script
        run: npm run build

      - run: ls -asl dist

      - name: ğŸš€ Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 18
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
